version: "3"

services:
     web:
            build: .
            ports:
                - 9000:80       
            depends_on:
                    - db
     db:
         image: "mcr.microsoft.com/mssql/server"
         container_name: mssql             
         environment:
             SA_PASSWORD: "arm!nder1"
             ACCEPT_EULA: "Y"
         ports:
             - 15785:1433
    

    #   db:
    #       image: "mcr.microsoft.com/mssql/server"
    #       container_name: mssql
    #       ports: 
    #         - 1433:1433
    #       environment:
    #           SA_PASSWORD: "arm!nder1"
    #           ACCEPT_EULA: "Y"
    #  db:
    #     build:
    #         context: D:\BlogService\BlogService
    #         dockerfile: dockerfile.dev1
    #     environment:
    #         SA_PASSWORD: "arm!nder1"
    #         ACCEPT_EULA: "Y"
    #     ports:
    #         - 15785:1433